[package]
name = "libmpegts"
version = "0.2.0"
authors = ["Cesbo Developers Team"]
description = "MPEG-TS Library"
documentation = "https://docs.rs/libmpegts"
repository = "https://github.com/cesbo/libmpegts"
edition = "2024"
license = "MIT"
readme = "README.md"
keywords = ["mpegts", "dvb"]

[dependencies]
textcode = "0.3"
