[package]
name = "mpegts"
version = "0.2.0-beta.1"
authors = ["Cesbo Developers Team"]
description = "MPEG-TS Library"
documentation = "https://docs.rs/libmpegts"
repository = "https://github.com/cesbo/libmpegts"
edition = "2024"
license = "MIT"
readme = "README.md"

[dependencies]
bytes = "1"
textcode = "0.3"
